[package]
name = "wait_queue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
taskctx = { path = "../taskctx" }
run_queue = { path = "../run_queue" }
spinbase = { path = "../../crates/spinbase" }
