[package]
name = "userboot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
task = { path = "../task" }
run_queue = { path = "../run_queue" }
fork = { path = "../fork" }
